HR_SKILLS = [
    # Recruitment & Talent Acquisition
    "recruitment",
    "talent acquisition",
    "sourcing",
    "candidate sourcing",
    "headhunting",
    "screening",
    "resume screening",
    "interviewing",
    "stakeholder management",
    "offer management",
    "offer negotiation",
    "joining formalities",
    "campus hiring",
    "bulk hiring",
    "lateral hiring",
    "executive hiring",
    "vendor management",
    "recruitment lifecycle",
    "end to end recruitment",
    "talent pipeline",

    # HR Operations
    "hr operations",
    "employee lifecycle",
    "employee engagement",
    "employee relations",
    "grievance handling",
    "disciplinary actions",
    "attendance management",
    "leave management",
    "exit management",
    "offboarding",
    "onboarding",
    "background verification",
    "documentation",
    "policy administration",
    "employee records",
    "hr administration",

    # Payroll & Compensation
    "payroll",
    "salary processing",
    "compensation",
    "benefits administration",
    "full and final settlement",
    "fnf settlement",
    "pf",
    "epf",
    "esi",
    "professional tax",
    "income tax",
    "ctc",
    "salary structure",
    "variable pay",
    "bonus administration",

    # Compliance & Labour Law
    "compliance",
    "statutory compliance",
    "labour law",
    "factory act",
    "shops and establishments act",
    "minimum wages",
    "payment of wages",
    "gratuity",
    "industrial relations",
    "labour welfare",
    "legal compliance",
    "audit",
    "internal audit",

    # HR Systems
    "workday",
    "sap",
    "sap hcm",
    "successfactors",
    "oracle hcm",
    "peoplesoft",
    "hrms",
    "hcm",
    "ats",
    "naukri",
    "linkedin recruiter",
    "foundit",
    "zoho people",
    "darwinbox",

    # Performance & Learning
    "performance management",
    "performance appraisal",
    "goal setting",
    "okr",
    "kpi",
    "training",
    "learning and development",
    "l&d",
    "succession planning",
    "career development",

    # Reporting & Analytics
    "hr analytics",
    "people analytics",
    "dashboard",
    "reporting",
    "excel",
    "advanced excel",
    "pivot table",
    "vlookup",
    "power query",
    "data analysis",
    "data visualization",
    "power bi",
    "tableau",

    # Employee Experience
    "employee satisfaction",
    "engagement survey",
    "culture building",
    "wellness program",
    "diversity",
    "inclusion",
    "dei",

    # HR Business Partner
    "hrbp",
    "business partnering",
    "workforce planning",
    "organization development",
    "change management",

    # General
    "communication",
    "negotiation",
    "stakeholder management",
    "account management",
    "problem solving",
    "conflict resolution",
    "time management",
    "team management",
    "leadership",
    "project management"
]